# Generated by Django 3.0 on 2020-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200901_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Mygallery'),
        ),
    ]
